name: Deploy to Google Cloud

on:
  push:
    branches: [ master ]

jobs:
  deploy_to_gc:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy and restart server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USER }}
          key: ${{ secrets.KEY }}
          script: |
            cd /home/ashishpadakannaya/578Yelp
            git pull --rebase
            source /home/ashishpadakannaya/venv/bin/activate
            pip install -r requirements.txt
            deactivate
            sudo systemctl restart nginx
            sudo supervisorctl reload
